"use client";
import "./globals.css";
import { useEffect } from "react";
import Aos from "aos";
import "aos/dist/aos.css";
//export const metadata = {
// title: 'Create Next App',
//description: 'Generated by create next app',
//}

export default function RootLayout({ children }) {
  return (
    useEffect(() => {
      Aos.init({
        duration: 800,
        once: false,
      });
    }),
    useEffect(() => {
      import("lightbox2/dist/js/lightbox-plus-jquery");
    }, []),
    useEffect(() => {
      import("bootstrap/dist/js/bootstrap.bundle.min.js");
    }, []),
    (
      <html lang="en">
        <body>
       
         {children}
         
         
        </body>
      </html>
    )
  );
}
